import { z } from 'zod';
// Подставь точное имя автогенерированной схемы пользователя (UserSchema или UserModelSchema)
import { UserSchema } from '../../generated/zod/index.js';

/**
 * Base student fields extracted directly from the autogenerated Prisma-Zod schema.
 */
const BaseStudentFields = UserSchema.pick({
  id: true,
  firstName: true,
  lastName: true,
  phoneNumber: true,
  createdAt: true,
});

export type BaseStudentType = z.infer<typeof BaseStudentFields>;

/**
 * Extended Student DTO containing essential dashboard statistics for the instructor.
 */
export interface StudentWithStatsDTO extends BaseStudentType {
  stats: {
    totalLessons: number;
    nextLessonAt: Date | null;
    hasActiveBooking: boolean;
  };
}

/**
 * Response array containing all active students assigned to the logged-in instructor.
 */
export type InstructorStudentsResponseDTO = StudentWithStatsDTO[];

/**
 * Single student mutation action response wrapper.
 */
export interface StudentMutationResponseDTO {
  message: string;
  student: BaseStudentType;
}